### ISSUE TITLE
domínio github.io | github.com

### ISSUE THREAD

**Issue by felipesousa** [devedmo/devedmo.github.io#1]
Brother, uma perguntinha simples, quando eu for subir meu projeto pro github, ele tem que ser prioritariamente github.io ou pode ser também github.com ?

**Comment by devedmo** [comment]
sempre github.io pois ele é o (github-pages)

Lembrando que se for site de repositorio tem que criar uma branch chamada gh-pages
E se for o site do autor como é o meu basta jogar no master mesmo.

**Comment by felipesousa** [comment]
Ah beleza.. Vlew :')
