### ISSUE TITLE
Widget's

### ISSUE THREAD

**Issue by felipesousa** [devedmo/devedmo.github.io#2]
Brother eu estava dando uma olhada no site e pensei em algo que pode ser legal de se inserir, eu vi no blog do Zeno e achei interessante e prático, na página de PROJETOS/, poderia ser inserir widgets do github e tudo mais. 

 Fica da hora e eu acho bem interessante, conhece? Abraço.

**Comment by devedmo** [comment]
É isso ai @felipesousa  já está implementado...como não estou direto conectado acabo esquecendo de enviar para o github, além disso eu criei um scipt em node pra toda vez que eu criar um projeto novo ele criar lá uma 'tab' com as informações do projeto.

Mas valeu pelo toque é bem por ai =)

**Comment by felipesousa** [comment]
Opa! Obrigado.. É isso ai, no meu eu implementei eles também, eu achei bem pratico e funcional. Vlew
